# -*- coding: utf-8 -*-
import logging
import os

from PyQt5.QtCore import QSize
# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import QSpacerItem, QSlider, QPushButton, QAction, QStatusBar, QProgressBar, QSpinBox, \
    QCheckBox, QGroupBox, QTextEdit, QStackedLayout, QStackedWidget, QTabWidget, QLineEdit
from PyQt5 import QtCore, QtGui
from PyQt5.QtGui import QIcon, QPixmap
from qtpy import QtWidgets

from paths import img_files
from src.ui.custom.WaveFormViewer import VolumeVisualiser
# from pyqt_music_player_widget import MusicPlayerWidget
from src.ui.custom.file.FileListItem import *
from src.ui.custom.GifLabel import GifLabel
from src.ui.custom.file.FileListWidget import FileListWidget
from src.ui.custom.zone.ZoneListWidget import ZoneListWidget
from src.ui.style_sheets import *
from src.ui.custom.ProgressIndacator import IndicatorProgressBar

logger = logging.getLogger(__name__)

blue_color = """
                                       QPushButton {
                                           background-color: #2979FE;
                                       }
                                       QPushButton:pressed {
                                           background-color: #005cb2;
                                       }
                                       """


class Ui_MainWindow(object):
    zone_buttons_layout: QHBoxLayout
    progress_indicator: IndicatorProgressBar
    list_scale_slider: QSlider
    text_edit_buttons_layout: QVBoxLayout
    right_vertical_layout: QVBoxLayout
    center_vertical_layout: QVBoxLayout
    left_vertical_layout: QVBoxLayout
    selected_voice_text: QLabel
    KSB_label_layout: QHBoxLayout
    update_volume_on_oranges_btn: QPushButton
    voice_select_btn: QPushButton
    zone_rename_btn: QPushButton
    auto_search_zones_btn: QPushButton
    zone_remove_btn: QPushButton
    zone_add_btn: QPushButton
    search_input: QLineEdit
    sort_by_date_btn: QPushButton
    sort_by_name_btn: QPushButton
    upload_custom_file_btn: QPushButton
    zone_list_container: QVBoxLayout
    file_list_widget: FileListWidget
    add_file_buttons_layout: QHBoxLayout
    zone_list_label: QLabel
    zone_list_widget: ZoneListWidget
    play_local_btn: QPushButton
    playback_layout: QVBoxLayout
    statusbar: QStatusBar
    progressBar: QProgressBar
    KSB_label: QLabel
    repeat_label: QLabel
    repeat_spin_box: QSpinBox
    repeat_check_box: QCheckBox
    volume_label: QLabel
    central_widget: QWidget
    volume_slider: QSlider
    play_btn: QPushButton
    stop_btn: QPushButton
    playback_gb: QGroupBox
    record_btn: QPushButton
    realtime_button: QPushButton
    stop_realtime_button: QPushButton
    main_text_edit_field: QTextEdit
    text_to_file_btn: QPushButton
    mic_usage_indicator: GifLabel

    def __init__(self):
        self.list_scale_controls_layout: QHBoxLayout
        self.zone_refresh_btn: QPushButton

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setMinimumSize(1000, 640)

        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setObjectName("centralwidget")
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.KSB_label_layout = QHBoxLayout()
        self.KSB_label = QtWidgets.QLabel()
        self.KSB_label_layout.addWidget(self.KSB_label, 1)

        self.playback_gb = self._build_playback_panel()
        self.broadcast_gb = self._build_broadcast_panel()
        self.filelist_tab_widget = self._build_file_list_panel()
        self.add_file_gb = self._build_add_file_panel()
        self.zone_list_container = self._build_zone_panel()
        self._assemble_main_layout(MainWindow)

        self.retranslate_ui(MainWindow)

    def _build_playback_panel(self) -> QGroupBox:
        gb = QtWidgets.QGroupBox()

        self.play_btn = QtWidgets.QPushButton(gb)
        self.play_btn.setMinimumHeight(50)

        self.stop_btn = QtWidgets.QPushButton(gb)
        self.stop_btn.setMinimumHeight(50)

        self.volume_label = QtWidgets.QLabel(gb)

        self.volume_slider = QtWidgets.QSlider(gb)
        self.volume_slider.setOrientation(QtCore.Qt.Horizontal)
        self.volume_slider.setMaximum(100)
        self.volume_slider.setMinimum(1)
        self.volume_slider.setValue(100)

        self.update_volume_on_oranges_btn = QPushButton()

        volume_slider_layout = QHBoxLayout()
        volume_slider_layout.addWidget(self.volume_slider, 10)
        volume_slider_layout.addWidget(self.update_volume_on_oranges_btn, 1)

        self.repeat_check_box = QtWidgets.QCheckBox(gb)
        self.repeat_label = QtWidgets.QLabel(gb)
        self.repeat_spin_box = QtWidgets.QSpinBox(gb)
        self.mic_usage_indicator = GifLabel()

        repeat_row = QHBoxLayout()
        repeat_row.addWidget(self.repeat_check_box)
        repeat_row.addStretch()
        repeat_row.addWidget(self.repeat_label)
        repeat_row.addWidget(self.repeat_spin_box)
        repeat_row.addWidget(self.mic_usage_indicator)

        layout = QtWidgets.QVBoxLayout(gb)
        layout.setSpacing(10)
        layout.setContentsMargins(12, 12, 12, 12)
        layout.addWidget(self.play_btn)
        layout.addWidget(self.stop_btn)
        layout.addWidget(self.volume_label)
        layout.addLayout(volume_slider_layout)
        layout.addLayout(repeat_row)
        return gb

    def _build_broadcast_panel(self) -> QGroupBox:
        self.realtime_button = QtWidgets.QPushButton()
        self.stop_realtime_button = QtWidgets.QPushButton()

        gb = QtWidgets.QGroupBox("Трансляция")
        layout = QtWidgets.QVBoxLayout(gb)
        layout.addWidget(self.realtime_button, 1)
        layout.addWidget(self.stop_realtime_button, 1)
        return gb

    def _build_file_list_panel(self) -> QTabWidget:
        self.file_list_widget = FileListWidget(self.central_widget)
        self.file_list_widget.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)

        self.search_input = QLineEdit()
        self.search_input.setPlaceholderText("Поиск файла…")
        self.search_input.setMinimumHeight(40)
        self.search_input.setClearButtonEnabled(True)

        self.sort_by_name_btn = QtWidgets.QPushButton(" По имени")
        self.sort_by_name_btn.setObjectName("ghost")
        self.sort_by_date_btn = QtWidgets.QPushButton(" По дате")
        self.sort_by_date_btn.setObjectName("ghost")

        self.list_scale_slider = QtWidgets.QSlider(Qt.Horizontal)
        self.list_scale_slider.setMinimum(1)
        self.list_scale_slider.setMaximum(4)
        self.list_scale_slider.setFixedHeight(25)
        self.list_scale_slider.setFixedWidth(50)

        text_field = QLabel('масштаб')
        text_field.setFixedHeight(20)

        self.list_scale_controls_layout = QHBoxLayout()
        self.list_scale_controls_layout.setContentsMargins(0, 0, 0, 0)
        self.list_scale_controls_layout.addWidget(text_field)
        self.list_scale_controls_layout.addWidget(self.list_scale_slider)

        list_top_controls_layout = QtWidgets.QHBoxLayout()
        list_top_controls_layout.setSpacing(8)
        list_top_controls_layout.addWidget(self.search_input, 1)
        list_top_controls_layout.addWidget(self.sort_by_name_btn)
        list_top_controls_layout.addWidget(self.sort_by_date_btn)
        list_top_controls_layout.addLayout(self.list_scale_controls_layout)

        self.current_files_tab = QWidget()
        self.current_files_tab.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        current_files_layout = QVBoxLayout(self.current_files_tab)
        current_files_layout.setContentsMargins(12, 12, 12, 12)
        current_files_layout.setSpacing(8)
        current_files_layout.addLayout(list_top_controls_layout, 0)
        current_files_layout.addWidget(self.file_list_widget, 1)

        self.scenarios_tab = QWidget()
        self.scenarios_tab.setMaximumWidth(900)
        self.scenarios_layout = QVBoxLayout(self.scenarios_tab)

        tab_widget = QtWidgets.QTabWidget(self.central_widget)
        tab_widget.addTab(self.current_files_tab, "Файлы")
        tab_widget.addTab(self.scenarios_tab, "сценарии")
        return tab_widget

    def _build_add_file_panel(self) -> QGroupBox:
        self.upload_custom_file_btn = QtWidgets.QPushButton('Загрузить аудиофайл')
        self.add_file_from_mic_record_btn = QtWidgets.QPushButton('Записать с микрофона')
        self.add_file_from_text_btn = QtWidgets.QPushButton('Озвучить из текста')
        self.progress_indicator = IndicatorProgressBar(self.central_widget)

        add_file_buttons_layout = QtWidgets.QHBoxLayout()
        add_file_buttons_layout.addWidget(self.upload_custom_file_btn, 2)
        add_file_buttons_layout.addWidget(self.add_file_from_mic_record_btn, 2)
        add_file_buttons_layout.addWidget(self.add_file_from_text_btn, 2)
        add_file_buttons_layout.addStretch(1)
        add_file_buttons_layout.addWidget(self.progress_indicator, 1)

        # --- текст → файл ---
        self.main_text_edit_field = QtWidgets.QTextEdit(self.central_widget)
        self.selected_voice_text = QtWidgets.QLabel()
        self.voice_select_btn = QToolButton()
        self.text_to_file_btn = QtWidgets.QPushButton()

        text_edit_buttons_layout = QtWidgets.QHBoxLayout()
        text_edit_buttons_layout.addWidget(self.selected_voice_text)
        text_edit_buttons_layout.addWidget(self.voice_select_btn)
        text_edit_buttons_layout.addStretch(1)
        text_edit_buttons_layout.addWidget(self.text_to_file_btn)

        add_file_from_text_layout = QVBoxLayout()
        add_file_from_text_layout.addWidget(self.main_text_edit_field, 10)
        add_file_from_text_layout.addLayout(text_edit_buttons_layout, 1)

        add_file_from_text_widget = QWidget()
        add_file_from_text_widget.setLayout(add_file_from_text_layout)

        # --- запись с микрофона ---
        self.record_btn = QtWidgets.QPushButton()
        self.volume_visualiser = VolumeVisualiser(self.central_widget)
        self.record_timer_label = QLabel("00:00:00")
        self.record_timer_label.setFont(QFont("Impact", 16, 1))

        add_from_mic_record_layout = QHBoxLayout()
        add_from_mic_record_layout.addWidget(self.record_timer_label, 1)
        add_from_mic_record_layout.addWidget(self.volume_visualiser, 4)
        add_from_mic_record_layout.addWidget(self.record_btn, 1)

        add_from_mic_record_widget = QWidget()
        add_from_mic_record_widget.setLayout(add_from_mic_record_layout)

        # --- stacked + переключение ---
        self.stacked_widget = QStackedWidget()
        self.stacked_widget.hide()
        self.stacked_widget.addWidget(add_file_from_text_widget)
        self.stacked_widget.addWidget(add_from_mic_record_widget)

        gb = QtWidgets.QGroupBox("Добавление файла")
        gb.setSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        gb.setStyleSheet("QGroupBox { padding-bottom: 0px; }")
        self.add_file_layout = QtWidgets.QVBoxLayout(gb)
        self.add_file_layout.addLayout(add_file_buttons_layout, 1)
        self.add_file_layout.addWidget(self.stacked_widget, 2)

        def update_button_styles(active_button):
            if active_button == 'text':
                self.add_file_from_text_btn.setStyleSheet(
                    "border: 1px solid #2979FE; border-radius: 8px; background-color: transparent;")
                self.add_file_from_mic_record_btn.setStyleSheet(blue_color_btn())
            elif active_button == 'mic':
                self.add_file_from_text_btn.setStyleSheet(blue_color_btn())
                self.add_file_from_mic_record_btn.setStyleSheet(
                    "border: 1px solid #2979FE; border-radius: 8px; background-color: transparent;")

        def show_text_to_file_layout():
            if self.stacked_widget.currentIndex() == 0 and self.stacked_widget.isVisible():
                self.stacked_widget.hide()
                gb.setFixedHeight(60)
            else:
                self.stacked_widget.setCurrentIndex(0)
                self.stacked_widget.show()
                gb.setFixedHeight(add_file_from_text_widget.sizeHint().height())
                update_button_styles("text")

        def show_mic_record_layout():
            if self.stacked_widget.currentIndex() == 1 and self.stacked_widget.isVisible():
                self.stacked_widget.hide()
                gb.setFixedHeight(60)
            else:
                self.stacked_widget.setCurrentIndex(1)
                self.stacked_widget.show()
                gb.setFixedHeight(150)
                update_button_styles("mic")

        self.add_file_from_text_btn.clicked.connect(show_text_to_file_layout)
        self.add_file_from_mic_record_btn.clicked.connect(show_mic_record_layout)
        return gb

    def _build_zone_panel(self) -> QVBoxLayout:
        self.zone_list_label = QtWidgets.QLabel()

        self.auto_search_zones_btn = QtWidgets.QPushButton()
        self.zone_add_btn = QtWidgets.QPushButton()
        self.zone_refresh_btn = QtWidgets.QPushButton()

        self.zone_buttons_layout = QtWidgets.QHBoxLayout()
        self.zone_buttons_layout.addWidget(self.auto_search_zones_btn)
        self.zone_buttons_layout.addWidget(self.zone_add_btn)
        self.zone_buttons_layout.addWidget(self.zone_refresh_btn)

        self.zone_process_indicator = IndicatorProgressBar(self.central_widget)
        self.zone_list_widget = ZoneListWidget(self.central_widget)
        self.zone_list_widget.setMinimumWidth(200)

        layout = QtWidgets.QVBoxLayout()
        layout.addWidget(self.zone_list_label)
        layout.addLayout(self.zone_buttons_layout)
        layout.addWidget(self.zone_process_indicator)
        layout.addWidget(self.zone_list_widget)
        return layout

    def _assemble_main_layout(self, MainWindow) -> None:
        # Левая панель — фиксированная ширина как в preview_real
        left_widget = QtWidgets.QWidget()
        left_widget.setFixedWidth(260)
        self.left_vertical_layout = QtWidgets.QVBoxLayout(left_widget)
        self.left_vertical_layout.setContentsMargins(0, 0, 0, 0)
        self.left_vertical_layout.setSpacing(12)
        self.left_vertical_layout.addLayout(self.KSB_label_layout)
        self.left_vertical_layout.addWidget(self.playback_gb)
        self.left_vertical_layout.addWidget(self.broadcast_gb)
        self.left_vertical_layout.addStretch()

        # Центральная панель — растягивается
        filelist_container_layout = QtWidgets.QVBoxLayout()
        filelist_container_layout.setSpacing(8)
        filelist_container_layout.addWidget(self.filelist_tab_widget, 1)
        filelist_container_layout.addWidget(self.add_file_gb)

        center_widget = QtWidgets.QWidget()
        self.center_vertical_layout = QtWidgets.QVBoxLayout(center_widget)
        self.center_vertical_layout.setContentsMargins(0, 0, 0, 0)
        self.center_vertical_layout.addLayout(filelist_container_layout)

        # Правая панель — фиксированная ширина
        right_widget = QtWidgets.QWidget()
        right_widget.setFixedWidth(300)
        self.right_vertical_layout = QtWidgets.QVBoxLayout(right_widget)
        self.right_vertical_layout.setContentsMargins(0, 0, 0, 0)
        self.right_vertical_layout.addLayout(self.zone_list_container)

        self.progressBar = QtWidgets.QProgressBar(self.central_widget)
        self.progressBar.setMaximumHeight(25)

        main_horizontal_layout = QHBoxLayout()
        main_horizontal_layout.setSpacing(16)
        main_horizontal_layout.addWidget(left_widget)
        main_horizontal_layout.addWidget(center_widget, 1)
        main_horizontal_layout.addWidget(right_widget)

        main_vertical_layout = QVBoxLayout(self.central_widget)
        main_vertical_layout.setContentsMargins(16, 16, 16, 16)
        main_vertical_layout.setSpacing(8)
        main_vertical_layout.addLayout(main_horizontal_layout)
        main_vertical_layout.addWidget(self.progressBar)

        MainWindow.setCentralWidget(self.central_widget)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def set_volume(self):
        logger.info(self.volume_slider.value())
        self.volume_label.setText(f'громкость {str(self.volume_slider.value())} %')
        if self.volume_slider.value() <= 100:
            self.volume_slider.setStyleSheet(volume_slider_style_default())
        else:
            self.volume_slider.setStyleSheet(volume_slider_style_overload())

    def retranslate_ui(self, MainWindow):

        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "КСБ Саундгард"))
        MainWindow.setWindowIcon(QtGui.QIcon(f'{paths.img_files}/logo (2).png'))

        self.update_volume_on_oranges_btn.setIcon(QIcon(f"{paths.img_files}{sep}arrow-up.png"))
        self.update_volume_on_oranges_btn.setToolTip("Обновить громкость на выбранных зонах-устройствах")
        self.update_volume_on_oranges_btn.setIconSize(QSize(15, 15))
        self.update_volume_on_oranges_btn.setStyleSheet(blue_color_btn())

        self.zone_list_label.setText("Зоны-Устройства")
        self.zone_list_label.font().setPointSize(10)

       # # self.main_text_edit_field.setPlaceholderText(
       #    #  _translate("MainWindow", "Напишите или вставьте сюда любой текст оповещения\n"
       #                               "укажите каким голосом его озвучить >> 'Выбрать голос'\n"
       #                               "Затем  нажмите кнопку 'Озвучить этот текст'. "
       #                               "\n(Файл с озвученым текстом появится в списке)"
       #                               "\nДалее, если вы хотите воспроизвести заранее "
       #                               "подготовленную речь на громкоговорителях \n"
       #                               ">> выберите нужный файл в списке сверху и"
       #                               "нажмите 'Проиграть'"))

        self.main_text_edit_field.setFont(QFont("Arial", 11))
        self.main_text_edit_field.setMaximumHeight(120)
        self.text_to_file_btn.setFont(QFont("Arial", 16, 1))
        self.text_to_file_btn.setIcon(QIcon(f"{paths.img_files}{sep}text-to-speech.png"))
        self.text_to_file_btn.setIconSize(QSize(32, 32))
        self.text_to_file_btn.setText(_translate("MainWindow", " Озвучить "))
        self.text_to_file_btn.setStyleSheet(f"""
                       QPushButton {{
                           border-radius: 8px;
                       }}
                       QPushButton:hover{{
                           border: 1px solid #2979FE;
                           border-radius: 8px;
                           background-color: transparent;
                       }}
                       """)

        self.voice_select_btn.setText(_translate("MainWindow", ":Выбрать голос"))
        self.voice_select_btn.setFont(QFont("Arial", 13))
        self.voice_select_btn.setStyleSheet(f"""
                       QToolButton {{
                           border-radius: 8px;
                       }}
                       QToolButton:hover{{
                           border: 1px solid #2979FE;
                           border-radius: 8px;
                           background-color: transparent;
                       }}
                       """)

        self.selected_voice_text.setText("мужской доброжелательный")
        self.selected_voice_text.setFixedHeight(25)
        self.selected_voice_text.setFont(QFont("Arial", 13))

        self.progressBar.setMaximumHeight(25)

        self.sort_by_name_btn.setMinimumHeight(40)
        self.sort_by_name_btn.setIcon(QIcon(f"{paths.img_files}/sort1.png"))
        self.sort_by_name_btn.setIconSize(QSize(22, 22))

        self.sort_by_date_btn.setMinimumHeight(40)
        self.sort_by_date_btn.setIcon(QIcon(f"{paths.img_files}/sort1.png"))
        self.sort_by_date_btn.setIconSize(QSize(22, 22))

        self.record_btn.setText(_translate("MainWindow", "Начать запись"))
        self.record_btn.setFont(QFont("Arial", 12))
        self.record_btn.setIcon(QIcon(f"{paths.img_files}/microphone-custom.png"))
        self.record_btn.setIconSize(QSize(50, 50))

        self.realtime_button.setText(_translate("MainWindow", "Говорить с микрофона"))
        self.realtime_button.setFont(QFont("Arial", 12))
        self.realtime_button.setFixedHeight(50)
        self.realtime_button.setIcon(QIcon(f"{paths.img_files}/broadcast-custom (1).png"))
        self.realtime_button.setIconSize(QSize(30, 30))

        self.stop_realtime_button.setText(_translate("MainWindow", "Прекратить вещание"))
        self.stop_realtime_button.setFont(QFont("Arial", 12))
        self.stop_realtime_button.setFixedHeight(50)
        self.stop_realtime_button.setIcon(QIcon(f"{paths.img_files}/broadcast-off-custom.png"))
        self.stop_realtime_button.setIconSize(QSize(30, 30))

        pixmap = QPixmap(os.path.join(paths.img_files, 'logo (2).png'))
        self.KSB_label.setPixmap(pixmap.scaledToHeight(72, Qt.SmoothTransformation))
        self.KSB_label.setAlignment(Qt.AlignLeft)
        self.KSB_label.setMaximumHeight(80)

        self.playback_gb.setTitle(_translate("MainWindow", "Воспроизведение"))
        self.playback_gb.setMinimumHeight(0)

        self.stop_btn.setText(_translate("MainWindow", "Остановить"))
        self.stop_btn.setFont(QFont("Arial", 16))

        self.play_btn.setText(_translate("MainWindow", "Проиграть"))
        self.play_btn.setFont(QFont("Arial", 16))

        self.repeat_check_box.setText(_translate("MainWindow", "Повторять"))
        self.repeat_check_box.setChecked(True)

        self.volume_label.setText(_translate("MainWindow", "Громкость"))
        self.repeat_label.setText(_translate("MainWindow", "раз"))

        self.repeat_spin_box.setStyleSheet(spin_box_text_size())
        self.repeat_spin_box.setFixedWidth(70)

        self.record_btn.setText('Начать запись')

        self.zone_add_btn.setMinimumHeight(40)
        self.zone_add_btn.setText('+ Зона')
        self.zone_add_btn.setToolTip('Добавить зону')
        self.zone_add_btn.setFont(QFont("Arial", 12))
        self.zone_add_btn.setStyleSheet(blue_color_btn())

        self.zone_refresh_btn.setMinimumHeight(40)
        self.zone_refresh_btn.setIcon(QIcon(f"{img_files}{sep}refresh.png"))
        self.zone_refresh_btn.setIconSize(QSize(22, 22))
        self.zone_refresh_btn.setToolTip('Обновить связь с зонами')
        self.zone_refresh_btn.setStyleSheet(blue_color_btn())

        self.auto_search_zones_btn.setMinimumHeight(40)
        self.auto_search_zones_btn.setText('Найти')
        self.auto_search_zones_btn.setToolTip('Автоматический поиск устройств')
        self.auto_search_zones_btn.setFont(QFont("Arial", 12))
        self.auto_search_zones_btn.setStyleSheet(blue_color_btn())

        self.upload_custom_file_btn.setMinimumHeight(44)
        self.upload_custom_file_btn.setStyleSheet(blue_color_btn())
        self.upload_custom_file_btn.setFont(QFont('Arial', 12))

        self.add_file_from_mic_record_btn.setMinimumHeight(44)
        self.add_file_from_mic_record_btn.setFont(QFont('Arial', 12))
        self.add_file_from_mic_record_btn.setStyleSheet(blue_color_btn())

        self.add_file_from_text_btn.setMinimumHeight(44)
        self.add_file_from_text_btn.setFont(QFont('Arial', 12))
        self.add_file_from_text_btn.setStyleSheet(blue_color_btn())

        # self.text_to_file_btn.setStyleSheet(blue_color_btn())
        self.stop_btn.setStyleSheet(blue_color_btn())
        self.play_btn.setStyleSheet(blue_color_btn())
        # self.voice_select_btn.setStyleSheet(blue_color_btn())

        self.record_btn.setStyleSheet(stop_realtime_btn_state1())
        self.realtime_button.setStyleSheet(stop_realtime_btn_state1())
        self.stop_realtime_button.setStyleSheet(stop_realtime_btn_state1())

        self.repeat_label.setFont(QFont("Tahoma", 14))
        self.repeat_check_box.setFont(QFont("Tahoma", 14))
